classdef Fluo_1pix < handle
    % Generic Pixelfly class
    
    properties
        
        pics_path
        
    end
    
    properties (Dependent = true)
       
        pic_at
        
        pic_at_bg
        
        pic_cor
        
    end
    
    properties % GUI
        
        dpg
        
    end
    
    properties % parent Data class
       
        parent
        
    end
    
    methods
        
        function obj = Fluo_1pix(pics_path)
            
            obj = obj@handle;
            
            obj.pics_path=pics_path;
            
            obj.pic_cor = obj.get_pic_cor;
            
        end
        
        function display_gui(obj)
            
            % initialize Show GUI
            
            obj.dpg.h = figure(...
                'Name'                ,'Show pic Main' ...
                ,'NumberTitle'        ,'off' ...
                ,'Position'           ,[2 144 1000 800] ... %,'MenuBar'     ,'none'...
                );
            
            %%% Camera & Treatment type panel %%%
            
            c_ofs = 20;
            r_ofs = 20;
            c_wth = 152;
            r_wth = 760;
            
            obj.dpg.hsp1 = uipanel(...
                'Parent'              ,obj.dpg.h ...
                ,'Title'              ,'Show corrected pic' ...
                ,'TitlePosition'      ,'lefttop' ...
                ,'BackgroundColor'    ,Treatment.Default_parameters.Panel_BackgroundColor ...
                ,'ForegroundColor'    ,Treatment.Default_parameters.Panel_ForegroundColor ...
                ,'HighlightColor'     ,Treatment.Default_parameters.Panel_HighlightColor ...
                ,'ShadowColor'        ,Treatment.Default_parameters.Panel_ShadowColor ...
                ,'FontName'           ,Treatment.Default_parameters.Panel_FontName ...
                ,'FontSize'           ,Treatment.Default_parameters.Panel_FontSize ...
                ,'FontUnits'          ,Treatment.Default_parameters.Panel_FontUnits ...
                ,'FontWeight'         ,Treatment.Default_parameters.Panel_FontWeight ...
                ,'SelectionHighlight' ,Treatment.Default_parameters.Panel_SelectionHighlight ...
                ,'Units'              ,'pixels'...%Treatment.Default_parameters.Panel_Units ...
                ,'Position'           ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            obj.dpg.hsp1_1 = uipanel(...
                'Parent'              ,obj.dpg.hsp1 ...
                ,'Title'              ,'absorption' ...
                ,'TitlePosition'      ,'centertop' ...
                ,'BackgroundColor'    ,Treatment.Default_parameters.Panel_BackgroundColor ...
                ,'ForegroundColor'    ,Treatment.Default_parameters.Panel_ForegroundColor ...
                ,'HighlightColor'     ,Treatment.Default_parameters.Panel_HighlightColor ...
                ,'ShadowColor'        ,Treatment.Default_parameters.Panel_ShadowColor ...
                ,'FontName'           ,Treatment.Default_parameters.Panel_FontName ...
                ,'FontSize'           ,Treatment.Default_parameters.Panel_FontSize ...
                ,'FontUnits'          ,Treatment.Default_parameters.Panel_FontUnits ...
                ,'FontWeight'         ,Treatment.Default_parameters.Panel_FontWeight ...
                ,'SelectionHighlight' ,'on' ...
                ,'Units'              ,'pixels'...%Treatment.Default_parameters.Panel_Units ...
                ,'Selected'           ,'on' ...
                ,'Position'           ,[4 8 144 144] ...
                ,'ButtonDownFcn'      , @obj.dpg_hsp1_1_clb ...
                );
            
            obj.dpg.ax1_1 = axes(...
                 'Parent'             ,obj.dpg.hsp1_1 ...
                ,'Units'              ,'pixels'...%Treatment.Default_parameters.Axes_Units ...
                ,'Position'           ,[4 4 128 120] ...
                );
            
            obj.dpg.hsp1_2 = uipanel(...
                 'Parent'             ,obj.dpg.hsp1 ...
                ,'Title'              ,'background reference' ...
                ,'TitlePosition'      ,'centertop' ...
                ,'BackgroundColor'    ,Treatment.Default_parameters.Panel_BackgroundColor ...
                ,'ForegroundColor'    ,Treatment.Default_parameters.Panel_ForegroundColor ...
                ,'HighlightColor'     ,Treatment.Default_parameters.Panel_HighlightColor ...
                ,'ShadowColor'        ,Treatment.Default_parameters.Panel_ShadowColor ...
                ,'FontName'           ,Treatment.Default_parameters.Panel_FontName ...
                ,'FontSize'           ,Treatment.Default_parameters.Panel_FontSize ...
                ,'FontUnits'          ,Treatment.Default_parameters.Panel_FontUnits ...
                ,'FontWeight'         ,Treatment.Default_parameters.Panel_FontWeight ...
                ,'SelectionHighlight' ,'on' ...
                ,'Units'              ,'pixels'...%Treatment.Default_parameters.Panel_Units ...
                ,'Selected'           ,'off' ...
                ,'Position'           ,[4 158 144 144] ...
                ,'ButtonDownFcn'      , @obj.dpg_hsp1_2_clb ...
                );
            
            obj.dpg.ax1_2 = axes(...
                 'Parent'             ,obj.dpg.hsp1_2 ...
                ,'Units'              ,'pixels'...%Treatment.Default_parameters.Axes_Units ...
                ,'Position'           ,[4 4 128 120] ...
                );
            
            obj.dpg.hsp1_3 = uipanel(...
                 'Parent'             ,obj.dpg.hsp1 ...
                ,'Title'              ,'background signal' ...
                ,'TitlePosition'      ,'centertop' ...
                ,'BackgroundColor'    ,Treatment.Default_parameters.Panel_BackgroundColor ...
                ,'ForegroundColor'    ,Treatment.Default_parameters.Panel_ForegroundColor ...
                ,'HighlightColor'     ,Treatment.Default_parameters.Panel_HighlightColor ...
                ,'ShadowColor'        ,Treatment.Default_parameters.Panel_ShadowColor ...
                ,'FontName'           ,Treatment.Default_parameters.Panel_FontName ...
                ,'FontSize'           ,Treatment.Default_parameters.Panel_FontSize ...
                ,'FontUnits'          ,Treatment.Default_parameters.Panel_FontUnits ...
                ,'FontWeight'         ,Treatment.Default_parameters.Panel_FontWeight ...
                ,'SelectionHighlight' ,'on' ...
                ,'Units'              ,'pixels'...%Treatment.Default_parameters.Panel_Units ...
                ,'Selected'           ,'off' ...
                ,'Position'           ,[4 308 144 144] ...
                ,'ButtonDownFcn'      , @obj.dpg_hsp1_3_clb ...
                );
            
            obj.dpg.ax1_3 = axes(...
                 'Parent'             ,obj.dpg.hsp1_3 ...
                ,'Units'              ,'pixels'...%Treatment.Default_parameters.Axes_Units ...
                ,'Position'           ,[4 4 128 120] ...
                );
            
            obj.dpg.hsp1_4 = uipanel(...
                 'Parent'             ,obj.dpg.hsp1 ...
                ,'Title'              ,'reference' ...
                ,'TitlePosition'      ,'centertop' ...
                ,'BackgroundColor'    ,Treatment.Default_parameters.Panel_BackgroundColor ...
                ,'ForegroundColor'    ,Treatment.Default_parameters.Panel_ForegroundColor ...
                ,'HighlightColor'     ,Treatment.Default_parameters.Panel_HighlightColor ...
                ,'ShadowColor'        ,Treatment.Default_parameters.Panel_ShadowColor ...
                ,'FontName'           ,Treatment.Default_parameters.Panel_FontName ...
                ,'FontSize'           ,Treatment.Default_parameters.Panel_FontSize ...
                ,'FontUnits'          ,Treatment.Default_parameters.Panel_FontUnits ...
                ,'FontWeight'         ,Treatment.Default_parameters.Panel_FontWeight ...
                ,'SelectionHighlight' ,'on' ...
                ,'Units'              ,'pixels'...%Treatment.Default_parameters.Panel_Units ...
                ,'Selected'           ,'off' ...
                ,'Position'           ,[4 458 144 144] ...
                ,'ButtonDownFcn'      , @obj.dpg_hsp1_4_clb ...
                );
            
            obj.dpg.ax1_4 = axes(...
                'Parent'              ,obj.dpg.hsp1_4 ...
                ,'Units'              ,'pixels'...%Treatment.Default_parameters.Axes_Units ...
                ,'Position'           ,[4 4 128 120]...
                );
            
            obj.dpg.hsp1_5 = uipanel(...
                'Parent'             ,obj.dpg.hsp1 ...
                ,'Title'              ,'signal' ...
                ,'TitlePosition'      ,'centertop' ...
                ,'BackgroundColor'    ,Treatment.Default_parameters.Panel_BackgroundColor ...
                ,'ForegroundColor'    ,Treatment.Default_parameters.Panel_ForegroundColor ...
                ,'HighlightColor'     ,Treatment.Default_parameters.Panel_HighlightColor ...
                ,'ShadowColor'        ,Treatment.Default_parameters.Panel_ShadowColor ...
                ,'FontName'           ,Treatment.Default_parameters.Panel_FontName ...
                ,'FontSize'           ,Treatment.Default_parameters.Panel_FontSize ...
                ,'FontUnits'          ,Treatment.Default_parameters.Panel_FontUnits ...
                ,'FontWeight'         ,Treatment.Default_parameters.Panel_FontWeight ...
                ,'SelectionHighlight' ,'on' ...
                ,'Units'              ,'pixels'...%Treatment.Default_parameters.Panel_Units ...
                ,'Selected'           ,'off' ...
                ,'Position'           ,[4 608 144 144] ...
                ,'ButtonDownFcn'      , @obj.dpg_hsp1_5_clb ...
                );
            
            obj.dpg.ax1_5 = axes(...
                'Parent'              ,obj.dpg.hsp1_5 ...
                ,'Units'              ,'pixels'...%Treatment.Default_parameters.Axes_Units ...
                ,'Position'           ,[4 4 128 120] ...
                );
            
            %%%
            
            obj.dpg.hsp2 = uipanel(...
                'Parent'             ,obj.dpg.h ...
                ,'Title'              ,'Detailed View' ...
                ,'TitlePosition'      ,'lefttop' ...
                ,'BackgroundColor'    ,Treatment.Default_parameters.Panel_BackgroundColor ...
                ,'ForegroundColor'    ,Treatment.Default_parameters.Panel_ForegroundColor ...
                ,'HighlightColor'     ,Treatment.Default_parameters.Panel_HighlightColor ...
                ,'ShadowColor'        ,Treatment.Default_parameters.Panel_ShadowColor ...
                ,'FontName'           ,Treatment.Default_parameters.Panel_FontName ...
                ,'FontSize'           ,Treatment.Default_parameters.Panel_FontSize ...
                ,'FontUnits'          ,Treatment.Default_parameters.Panel_FontUnits ...
                ,'FontWeight'         ,Treatment.Default_parameters.Panel_FontWeight ...
                ,'SelectionHighlight' ,Treatment.Default_parameters.Panel_SelectionHighlight ...
                ,'Units'              ,'pixels'...%Treatment.Default_parameters.Panel_Units ...
                ,'Position'           ,[192 240 600 540] ...
                );
            
            obj.dpg.ax2_1 = axes(...
                 'Parent'             ,obj.dpg.hsp2 ...
                ,'Units'              ,'pixels'...%Treatment.Default_parameters.Axes_Units ...
                ,'Position'           ,[40 200 320 320] ...
                );
            
            obj.dpg.ax2_2 = axes(...
                'Parent'              ,obj.dpg.hsp2 ...
                ,'Units'              ,'pixels'...%Treatment.Default_parameters.Axes_Units ...
                ,'Position'           ,[40 40 320 120] ...
                );
            
            obj.dpg.ax2_3 = axes(...
                'Parent'              ,obj.dpg.hsp2 ...
                ,'Units'              ,'pixels'...%Treatment.Default_parameters.Axes_Units ...
                ,'Position'           ,[400 200 120 320] ...
                );
            
        end
        
        function dpg_hsp1_2_clb(obj,~,~)
            
        end
        
        function dpg_hsp1_1_clb(obj,~,~)
            
        end
        
        function dpg_hsp1_3_clb(obj,~,~)
            
        end
        
        function dpg_hsp1_4_clb(obj,~,~)
            
        end
        
        function dpg_hsp1_5_clb(obj,~,~)
            
        end
        
        function show(obj)
            
            % Show Pics
            
            h_fluo_img_at=findobj('Name','Fluorescence Image - Atoms');
            
            if isempty(h_fluo_img_at)
                
                h_fluo_img_at  = figure('Name','Fluorescence Image - Atoms','Position',[8,694,560,420],'NumberTitle','off');
                ax_fluo_img_at = axes('Parent',h_fluo_img_at);
                
            else
                
                tmp = get(h_fluo_img_at,'Children');
                ax_fluo_img_at = tmp(2);
                
            end
            
            h_fluo_img_at_bg=findobj('Name','Fluorescence Image - Atoms Background');
            
            if isempty(h_fluo_img_at_bg)
                
                h_fluo_img_at_bg  = figure('Name','Fluorescence Image - Atoms Background','Position',[8,182,560,420],'NumberTitle','off');
                ax_fluo_img_at_bg = axes('Parent',h_fluo_img_at_bg);
                
            else
                
                tmp = get(h_fluo_img_at_bg,'Children');
                ax_fluo_img_at_bg = tmp(2);
                
            end
            
            h_fluo_img_cor=findobj('Name','Fluorescence Image - Corrected');
            
            if isempty(h_fluo_img_cor)
                
                h_fluo_img_cor  = figure('Name','Fluorescence Image - Corrected','Position',[1349,695,560,420],'NumberTitle','off');
                ax_fluo_img_cor = axes('Parent',h_fluo_img_cor);
                
            else
                
                tmp = get(h_fluo_img_cor,'Children');
                ax_fluo_img_cor = tmp(2);
                
            end

            imagesc(obj.pic_at,'Parent',ax_fluo_img_at);
            caxis(ax_fluo_img_at,[200 600]);
            colorbar('peer',ax_fluo_img_at);
            axis(ax_fluo_img_at,'image')
            set(ax_fluo_img_at,'YDir','normal');
            
            imagesc(obj.pic_at_bg,'Parent',ax_fluo_img_at_bg);
            caxis(ax_fluo_img_at_bg,[200 600]);
            colorbar('peer',ax_fluo_img_at_bg);
            axis(ax_fluo_img_at_bg,'image')
            set(ax_fluo_img_at_bg,'YDir','normal');
            
            imagesc(obj.pic_cor,'Parent',ax_fluo_img_cor);
            caxis(ax_fluo_img_cor,[0 400]);
            colorbar('peer',ax_fluo_img_cor);
            axis(ax_fluo_img_cor,'image')
            set(ax_fluo_img_cor,'YDir','normal');
            
            
            set(h_fluo_img_at,'Visible','off')
            set(h_fluo_img_at_bg,'Visible','off')
            set(h_fluo_img_cor,'Visible','off')
            
            set(h_fluo_img_at,'Visible','on')
            set(h_fluo_img_at_bg,'Visible','on')
            set(h_fluo_img_cor,'Visible','on')
            
        end
        
        function fpic_cor = get_pic_cor(obj)
            
            fpic_cor = (obj.pic_at - obj.pic_at_bg);
            
        end
        
        function pic_at = get.pic_at(obj)
            
            path = [obj.pics_path,'\pic_at.mat'];
            
            load(path);
            
        end
        
        function pic_at_bg = get.pic_at_bg(obj)
            
            path = [obj.pics_path,'\pic_at_bg.mat'];
            
            load(path);
            
        end
        
        function pic_cor = get.pic_cor(obj)
            
            path = [obj.pics_path,'\pic_cor.mat'];
            
            load(path);
        
        end
        
        function set.pic_cor(obj,pic_cor)
            
            path = [obj.pics_path,'\pic_cor.mat'];
            
            save(path,'pic_cor');
            
        end
        
    end

end